### ISSUE TITLE
typing # on the first character of code crashes the program

### ISSUE THREAD

**Issue by ScienceKit** [IoeCmcomc/MCDatapacker#7] opened 2023-05-23 09:34 UTC
in my datapack i was writing away, when i did the following:
some command here that does something and is valid

then some place in the text i press enter:
some command here that 
|does something and is valid

Now my cursor is bottom left. Then i go to the first line to edit something:
|some command here that 
does something and is valid

That's all well and good, but when i comment that first line, instead of this:
#|some command here that 
does something and is valid

it just crashes.
!!! This only happens on the first line and only when i make a comment, off the top of my head i think the loop to color the text green give the string.find() function an adress of 0 and the exit condition is i == str.find() but str. find give -1 and it just keeps going and going into leaked memory
![image](https://github.com/IoeCmcomc/MCDatapacker/assets/127025473/b5dc62fa-95bf-4a31-8e32-5cf2200450b9)

**Comment by IoeCmcomc** [comment] 2023-05-24 02:24
Duplicate of #6

**Comment by IoeCmcomc** [comment] 2023-05-24 02:27
Despite being a duplicate, I will keep this issue open until a new version is released.

**Closed** 2023-06-22 16:23 UTC
Labels: bug, duplicate
